/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'mlm' at '6/6/16 9:03 AM' with Gradle 2.13
 *
 * @author mlm, @date 6/6/16 9:03 AM
 */
/*
import spock.lang.Specification

class ScriptToolTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        //ScriptTool st = new edu.uvm.banner.ScriptTool()
        when:
        def result = edu.uvm.banner.ScriptTool.testit()
        then:
        result == true
    }
}
*/
